/**
 * Template Service
 * Custom template system for export formatting with variables and conditional logic
 */

import AsyncStorage from '@react-native-async-storage/async-storage';
import { EnhancedTranscriptionItem, ExportFormat, ExportTemplate } from '../../types';

interface TemplateVariable {
  name: string;
  description: string;
  type: 'string' | 'number' | 'date' | 'boolean';
  defaultValue?: string;
}

interface ConditionalBlock {
  condition: string;
  content: string;
}

class TemplateService {
  private readonly STORAGE_KEY = 'export_templates';
  private readonly builtInTemplates: ExportTemplate[] = [
    {
      id: 'simple-text',
      name: 'Simple Text',
      format: 'txt',
      template: '{{transcription}}',
      variables: {},
    },
    {
      id: 'detailed-text',
      name: 'Detailed Text Report',
      format: 'txt',
      template: `Transcription Report
==================

Date: {{date}}
Time: {{time}}
Duration: {{duration}}
Category: {{category}}
Tags: {{tags}}
Confidence: {{confidence}}
Word Count: {{wordCount}}

Transcription:
--------------
{{transcription}}

---
Generated by Audio Transcription App`,
      variables: {},
    },
    {
      id: 'meeting-notes',
      name: 'Meeting Notes',
      format: 'txt',
      template: `Meeting Notes - {{date}}
========================

Meeting Details:
- Date: {{date}}
- Duration: {{duration}}
- Category: {{category}}

Attendees: {{attendees}}
Agenda: {{agenda}}

Discussion:
-----------
{{transcription}}

Action Items:
- {{actionItems}}

Next Meeting: {{nextMeeting}}`,
      variables: {
        attendees: 'Meeting attendees',
        agenda: 'Meeting agenda',
        actionItems: 'Action items from the meeting',
        nextMeeting: 'Next meeting date/time',
      },
    },
    {
      id: 'interview-summary',
      name: 'Interview Summary',
      format: 'txt',
      template: `Interview Summary
================

Candidate: {{candidateName}}
Position: {{position}}
Date: {{date}}
Duration: {{duration}}
Interviewer: {{interviewer}}

Interview Transcript:
--------------------
{{transcription}}

Assessment:
-----------
Technical Skills: {{technicalSkills}}
Communication: {{communication}}
Cultural Fit: {{culturalFit}}

Recommendation: {{recommendation}}

Notes: {{additionalNotes}}`,
      variables: {
        candidateName: 'Candidate name',
        position: 'Position being interviewed for',
        interviewer: 'Interviewer name',
        technicalSkills: 'Technical skills assessment',
        communication: 'Communication skills assessment',
        culturalFit: 'Cultural fit assessment',
        recommendation: 'Hiring recommendation',
        additionalNotes: 'Additional notes',
      },
    },
    {
      id: 'lecture-notes',
      name: 'Lecture Notes',
      format: 'txt',
      template: `Lecture Notes - {{subject}}
==========================

Course: {{course}}
Instructor: {{instructor}}
Date: {{date}}
Duration: {{duration}}
Topic: {{topic}}

Key Points:
-----------
{{keyPoints}}

Lecture Content:
---------------
{{transcription}}

Assignments:
-----------
{{assignments}}

Next Class: {{nextClass}}`,
      variables: {
        subject: 'Lecture subject',
        course: 'Course name',
        instructor: 'Instructor name',
        topic: 'Lecture topic',
        keyPoints: 'Key points from the lecture',
        assignments: 'Assignments given',
        nextClass: 'Next class information',
      },
    },
    {
      id: 'json-structured',
      name: 'Structured JSON',
      format: 'json',
      template: `{
  "metadata": {
    "title": "{{title}}",
    "date": "{{date}}",
    "duration": {{duration}},
    "category": "{{category}}",
    "tags": [{{tagsArray}}],
    "confidence": {{confidenceDecimal}},
    "wordCount": {{wordCount}}
  },
  "content": {
    "transcription": "{{transcription}}",
    "summary": "{{summary}}",
    "keyTopics": [{{keyTopics}}]
  },
  "analysis": {
    "sentiment": "{{sentiment}}",
    "language": "{{language}}",
    "speakerCount": {{speakerCount}}
  }
}`,
      variables: {
        title: 'Document title',
        summary: 'Content summary',
        keyTopics: 'Key topics (comma-separated)',
        sentiment: 'Content sentiment',
        language: 'Content language',
        speakerCount: 'Number of speakers',
      },
    },
  ];

  /**
   * Get all available templates
   */
  async getTemplates(): Promise<ExportTemplate[]> {
    try {
      const customTemplates = await this.getCustomTemplates();
      return [...this.builtInTemplates, ...customTemplates];
    } catch (error) {
      console.error('Failed to get templates:', error);
      return this.builtInTemplates;
    }
  }

  /**
   * Get templates for specific format
   */
  async getTemplatesForFormat(format: ExportFormat): Promise<ExportTemplate[]> {
    const allTemplates = await this.getTemplates();
    return allTemplates.filter(template => template.format === format);
  }

  /**
   * Get template by ID
   */
  async getTemplate(id: string): Promise<ExportTemplate | null> {
    const templates = await this.getTemplates();
    return templates.find(template => template.id === id) || null;
  }

  /**
   * Save custom template
   */
  async saveTemplate(template: ExportTemplate): Promise<void> {
    try {
      const customTemplates = await this.getCustomTemplates();
      
      // Check if template already exists
      const existingIndex = customTemplates.findIndex(t => t.id === template.id);
      
      if (existingIndex >= 0) {
        customTemplates[existingIndex] = template;
      } else {
        customTemplates.push(template);
      }

      await AsyncStorage.setItem(this.STORAGE_KEY, JSON.stringify(customTemplates));
    } catch (error) {
      console.error('Failed to save template:', error);
      throw error;
    }
  }

  /**
   * Delete custom template
   */
  async deleteTemplate(id: string): Promise<void> {
    try {
      const customTemplates = await this.getCustomTemplates();
      const filteredTemplates = customTemplates.filter(template => template.id !== id);
      
      await AsyncStorage.setItem(this.STORAGE_KEY, JSON.stringify(filteredTemplates));
    } catch (error) {
      console.error('Failed to delete template:', error);
      throw error;
    }
  }

  /**
   * Preview template with sample data
   */
  previewTemplate(template: ExportTemplate, sampleData?: Partial<EnhancedTranscriptionItem>): string {
    const mockItem: EnhancedTranscriptionItem = {
      id: 'sample-id',
      audioUri: 'sample-audio.wav',
      transcription: sampleData?.transcription || 'This is a sample transcription for preview purposes. It demonstrates how the template will look with actual content.',
      duration: sampleData?.duration || 120,
      createdAt: sampleData?.createdAt || new Date(),
      isProcessing: false,
      confidence: sampleData?.confidence || 0.85,
      tags: sampleData?.tags || ['sample', 'preview'],
      category: sampleData?.category || 'meeting',
      editHistory: [],
      audioQuality: {
        signalToNoiseRatio: 35,
        clarity: 0.8,
        volume: 0.7,
        backgroundNoise: 0.2,
        overallScore: 0.8,
      },
      processingTime: 5.2,
      wordTimestamps: [],
      speakerSegments: [],
      customMetadata: {},
      exportHistory: [],
      searchableText: 'sample preview transcription',
    };

    return this.applyTemplate(mockItem, template);
  }

  /**
   * Apply template to transcription item
   */
  applyTemplate(item: EnhancedTranscriptionItem, template: ExportTemplate): string {
    let content = template.template;

    // Prepare all available variables
    const variables = {
      ...template.variables,
      // Basic item data
      transcription: item.transcription,
      date: item.createdAt.toLocaleDateString(),
      time: item.createdAt.toLocaleTimeString(),
      datetime: item.createdAt.toLocaleString(),
      duration: this.formatDuration(item.duration),
      durationSeconds: item.duration.toString(),
      category: item.category,
      tags: item.tags.join(', '),
      tagsArray: item.tags.map(tag => `"${tag}"`).join(', '),
      confidence: item.confidence ? `${Math.round(item.confidence * 100)}%` : 'N/A',
      confidenceDecimal: item.confidence?.toString() || '0',
      wordCount: item.transcription.split(/\s+/).filter(word => word.trim()).length.toString(),
      
      // Metadata
      id: item.id,
      processingTime: item.processingTime?.toFixed(1) || 'N/A',
      
      // Audio quality
      audioQuality: item.audioQuality?.overallScore ? `${Math.round(item.audioQuality.overallScore * 100)}%` : 'N/A',
      signalToNoise: item.audioQuality?.signalToNoiseRatio?.toFixed(1) || 'N/A',
      
      // Timestamps
      createdTimestamp: item.createdAt.getTime().toString(),
      isoDate: item.createdAt.toISOString(),
      
      // Calculated fields
      estimatedReadingTime: Math.ceil(item.transcription.split(/\s+/).length / 200).toString(), // ~200 WPM
      characterCount: item.transcription.length.toString(),
    };

    // Process conditional blocks first
    content = this.processConditionalBlocks(content, variables);

    // Replace template variables
    Object.entries(variables).forEach(([key, value]) => {
      const regex = new RegExp(`{{${key}}}`, 'g');
      content = content.replace(regex, value || '');
    });

    // Clean up any remaining unreplaced variables
    content = content.replace(/{{[^}]+}}/g, '');

    return content;
  }

  /**
   * Get available template variables
   */
  getAvailableVariables(): TemplateVariable[] {
    return [
      { name: 'transcription', description: 'The transcription text', type: 'string' },
      { name: 'date', description: 'Creation date (localized)', type: 'date' },
      { name: 'time', description: 'Creation time (localized)', type: 'string' },
      { name: 'datetime', description: 'Full date and time', type: 'date' },
      { name: 'duration', description: 'Formatted duration (MM:SS)', type: 'string' },
      { name: 'durationSeconds', description: 'Duration in seconds', type: 'number' },
      { name: 'category', description: 'Transcription category', type: 'string' },
      { name: 'tags', description: 'Tags (comma-separated)', type: 'string' },
      { name: 'tagsArray', description: 'Tags as JSON array', type: 'string' },
      { name: 'confidence', description: 'Confidence percentage', type: 'string' },
      { name: 'confidenceDecimal', description: 'Confidence as decimal', type: 'number' },
      { name: 'wordCount', description: 'Number of words', type: 'number' },
      { name: 'characterCount', description: 'Number of characters', type: 'number' },
      { name: 'estimatedReadingTime', description: 'Estimated reading time (minutes)', type: 'number' },
      { name: 'audioQuality', description: 'Overall audio quality percentage', type: 'string' },
      { name: 'processingTime', description: 'AI processing time', type: 'string' },
    ];
  }

  /**
   * Validate template syntax
   */
  validateTemplate(template: string): { isValid: boolean; errors: string[] } {
    const errors: string[] = [];

    // Check for unclosed template variables
    const openBraces = (template.match(/{{/g) || []).length;
    const closeBraces = (template.match(/}}/g) || []).length;
    
    if (openBraces !== closeBraces) {
      errors.push('Mismatched template variable braces');
    }

    // Check for invalid variable names
    const variableRegex = /{{([^}]+)}}/g;
    let match;
    const availableVars = this.getAvailableVariables().map(v => v.name);
    
    while ((match = variableRegex.exec(template)) !== null) {
      const varName = match[1].trim();
      if (!availableVars.includes(varName) && !varName.startsWith('if:') && !varName.startsWith('endif')) {
        errors.push(`Unknown variable: ${varName}`);
      }
    }

    return {
      isValid: errors.length === 0,
      errors,
    };
  }

  /**
   * Create template from existing transcription
   */
  createTemplateFromItem(item: EnhancedTranscriptionItem, name: string, format: ExportFormat): ExportTemplate {
    const template: ExportTemplate = {
      id: `custom-${Date.now()}`,
      name,
      format,
      template: this.generateTemplateFromItem(item),
      variables: {},
    };

    return template;
  }

  /**
   * Get custom templates from storage
   */
  private async getCustomTemplates(): Promise<ExportTemplate[]> {
    try {
      const stored = await AsyncStorage.getItem(this.STORAGE_KEY);
      return stored ? JSON.parse(stored) : [];
    } catch (error) {
      console.error('Failed to get custom templates:', error);
      return [];
    }
  }

  /**
   * Process conditional blocks in template
   */
  private processConditionalBlocks(content: string, variables: Record<string, string>): string {
    // Simple conditional processing: {{if:variable}}content{{endif:variable}}
    const conditionalRegex = /{{if:([^}]+)}}(.*?){{endif:\1}}/gs;
    
    return content.replace(conditionalRegex, (match, condition, blockContent) => {
      const value = variables[condition];
      // Show content if variable exists and is not empty
      return (value && value.trim() !== '' && value !== 'N/A') ? blockContent : '';
    });
  }

  /**
   * Generate template from existing item
   */
  private generateTemplateFromItem(item: EnhancedTranscriptionItem): string {
    let template = `{{category}} - {{date}}
${'='.repeat(30)}

Duration: {{duration}}
Confidence: {{confidence}}
{{if:tags}}Tags: {{tags}}{{endif:tags}}

{{transcription}}

---
Word Count: {{wordCount}}
Processing Time: {{processingTime}}`;

    return template;
  }

  /**
   * Format duration helper
   */
  private formatDuration(seconds: number): string {
    const hours = Math.floor(seconds / 3600);
    const mins = Math.floor((seconds % 3600) / 60);
    const secs = Math.floor(seconds % 60);
    
    if (hours > 0) {
      return `${hours}:${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
    }
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  }
}

// Export singleton instance
export const templateService = new TemplateService();
export default templateService;